### ISSUE TITLE
能不能把持有份额在我的基金里显示出来？

### ISSUE THREAD

**Issue by klgd** [adams549659584/utools-fund#4]
因为份额都是手动添加的，再加上基金的交易一般都是第2天再会得出份额，所以手动添加不会那么及时，就导致很多时候记不得自己哪个基金份额更新了哪个没更新，如果能把份额显示出来会方便很多

**Comment by adams549659584** [comment]
加上发布了，等插件中心审核通过就会自动更新了，或者可以这里下载
https://github.com/adams549659584/utools-fund/releases/tag/v1.6.2
