### ISSUE TITLE
关于打包的咨询

### ISSUE THREAD

**Issue by Hermhades** [adams549659584/utools-fund#7]
咨询下utools打包的问题。源码下载下来没有index.html也没有preload.js。尝试了几次都无法运行成功。求指导
参考官方文档：https://www.u.tools/docs/developer/config.html#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE
（修改了获取基金预估净值的接口，想自己调试一下）

**Comment by adams549659584** [comment]
npm 或 yarn 安装依赖后，npm run dev 或 yarn dev ，会生成 dist 目录的，里面有，build的话，就npm run build

**Comment by Hermhades** [comment]
已成功，感谢~~
